--1. EN FAZLA OLAN MARKA VE MODEL.
USE CARPLATES;
SET STATISTICS IO ON;
SELECT TOP(1) COUNT(BRAND) AS MARKA_SAYISI, BRAND, MODEL 
FROM PLATES
GROUP BY BRAND, MODEL
ORDER BY COUNT(BRAND) DESC, COUNT(MODEL) DESC;

--EN FAZLA OLAN MARKA VE MODEL. ICIN INDEX YAPISI:>
CREATE NONCLUSTERED INDEX [IX4] ON [dbo].[PLATES]
(
	[BRAND] ASC,
	[MODEL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 70, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF);
--------------------------------------------------------------------------------------------------------

--2. EN AZ OLAN RENK.
SET STATISTICS IO ON;
SELECT TOP(1) COUNT(COLOR) AS RENK_ADETI, COLOR AS RENK
FROM PLATES
GROUP BY COLOR
HAVING COLOR IS NOT NULL AND COLOR <> '-'
ORDER BY COUNT(COLOR) ASC;
--EN AZ OLAN RENK ICIN INDEX YAPISI:>
CREATE NONCLUSTERED INDEX IX1
ON [dbo].[PLATES] ([COLOR])
--------------------------------------------------------------------------------------------------------

--3. LISANS TARIHI 2008 VEYA UST OLAN KAC MARKA VE MODEL OLDUGUNU BUL.
SET STATISTICS IO ON;
SELECT LICENCEDATE, COUNT(BRAND), COUNT(MODEL)
FROM PLATES
GROUP BY LICENCEDATE
HAVING DATEPART(YEAR, LICENCEDATE) > 2008
ORDER BY LICENCEDATE;
--LISANS TARIHI 2008 VEYA UST OLAN KAC MARKA VE MODEL OLDUGUNU BUL ICIN INDEX YAPISI:>
CREATE NONCLUSTERED INDEX [IX2] ON [dbo].[PLATES]
(
	[LICENCEDATE] ASC
)
INCLUDE([BRAND],[MODEL],[ID],[CARID],[PLATE],[CITYNR],[TITLE],[YEAR_],[FUEL],[SHIFTTYPE],[MOTORVOLUME],[MOTORPOWER],[COLOR],[CASETYPE]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 70, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY];
--------------------------------------------------------------------------------------------------------

--4. HANGI SEHIRDE HANGI MARKADAN KAC TANE VAR?
SET STATISTICS IO ON;
SELECT CITYNR, BRAND AS MARKA, COUNT(BRAND) AS MARKA_SAYISI
FROM PLATES
GROUP BY CITYNR, BRAND
ORDER BY CITYNR, BRAND;
--HANGI SEHIRDE HANGI MARKADAN KAC TANE VAR? ICIN INDEX YAPISI:>
CREATE NONCLUSTERED INDEX [IX3] ON [dbo].[PLATES]
(
	[CITYNR] ASC
)
INCLUDE([BRAND]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 70, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
--------------------------------------------------------------------------------------------------------
--5. EN FAZLA TERCIH EDILEN MOTOR HACMI
SET STATISTICS IO ON;
SELECT TOP(1) MOTORVOLUME AS EN_COK_TERCIH_EDILEN_MOTOR_HACMI, COUNT(MOTORVOLUME) AS TOPLAM_SAYISI
FROM PLATES
GROUP BY MOTORVOLUME
HAVING MOTORVOLUME IS NOT NULL AND MOTORVOLUME <> '-' AND MOTORVOLUME <> ''
ORDER BY COUNT(MOTORVOLUME) DESC;


--6. SEHIRLERE GORE EN FAZLA TERCIH EDILEN DUZ VITES TIPI
SET STATISTICS IO ON;
SELECT CITYNR, SHIFTTYPE AS EN_COK_TERCIH_EDILEN_VITES_TIPI, COUNT(SHIFTTYPE) AS TOPLAM_SAYISI
FROM PLATES
GROUP BY CITYNR, SHIFTTYPE
HAVING SHIFTTYPE IS NOT NULL AND SHIFTTYPE <> '-' AND SHIFTTYPE <> '' AND SHIFTTYPE = 'Düz Vites'
ORDER BY TOPLAM_SAYISI DESC;

--7. SEHIRLERE GORE EN FAZLA TERCIH EDILEN OTOMATIK VITES TIPI
SET STATISTICS IO ON;
SELECT CITYNR, SHIFTTYPE AS EN_COK_TERCIH_EDILEN_VITES_TIPI, COUNT(SHIFTTYPE) AS TOPLAM_SAYISI
FROM PLATES
GROUP BY CITYNR, SHIFTTYPE
HAVING SHIFTTYPE IS NOT NULL AND SHIFTTYPE <> '-' AND SHIFTTYPE <> '' AND SHIFTTYPE = 'Otomatik Vites'
ORDER BY TOPLAM_SAYISI DESC;

SET STATISTICS IO ON;
SELECT *
FROM PLATES
WHERE PLATE = '01 HVH 47';