--EN FAZLA OLAN MARKA VE MODEL
CREATE FUNCTION MAX_BRAND_AND_MODEL()
RETURNS TABLE
AS
RETURN(
SELECT TOP(1) COUNT(BRAND) AS MARKA_SAYISI, BRAND, MODEL 
FROM PLATES
GROUP BY BRAND, MODEL
ORDER BY COUNT(BRAND) DESC, COUNT(MODEL) DESC
);

--2. EN AZ OLAN RENK.
CREATE FUNCTION MIN_CAR_COLOR()
RETURNS TABLE
AS
RETURN(
SELECT TOP(1) COUNT(COLOR) AS RENK_ADETI, COLOR AS RENK
FROM PLATES
GROUP BY COLOR
HAVING COLOR IS NOT NULL AND COLOR <> '-'
ORDER BY COUNT(COLOR) ASC
);

--3. Lisans tarihi 2008 veya üst olan araçlarýn içerisinde lisans tarihi en üst olan aracýn lisans tarihi.
CREATE FUNCTION MAX_LICENCE_DATE()
RETURNS TABLE
AS
RETURN(
SELECT TOP(1) LICENCEDATE, COUNT(BRAND) BRAND_COUNT, COUNT(MODEL) MODEL_COUNT
FROM PLATES
GROUP BY LICENCEDATE
HAVING DATEPART(YEAR, LICENCEDATE) > 2008
ORDER BY LICENCEDATE
);

--Ýstanbul'da en az hangi araç var?
CREATE FUNCTION ISTANBUL_MIN_CAR()
RETURNS TABLE
AS
RETURN(
SELECT TOP(1) CITYNR, BRAND AS MARKA, COUNT(BRAND) AS MARKA_SAYISI
FROM PLATES
WHERE CITYNR = 36
GROUP BY CITYNR, BRAND
ORDER BY CITYNR, COUNT(BRAND) ASC
);

--5. EN FAZLA TERCIH EDILEN MOTOR HACMI
CREATE FUNCTION HIGH_MOTOR_VOLUME()
RETURNS TABLE
AS
RETURN(
SELECT TOP(1) MOTORVOLUME AS EN_COK_TERCIH_EDILEN_MOTOR_HACMI, COUNT(MOTORVOLUME) AS TOPLAM_SAYISI
FROM PLATES
GROUP BY MOTORVOLUME
HAVING MOTORVOLUME IS NOT NULL AND MOTORVOLUME <> '-' AND MOTORVOLUME <> ''
ORDER BY COUNT(MOTORVOLUME) DESC
);

--ISTANBUL'DA EN FAZLA TERCIH EDILEN DUZ VITES TIPI
CREATE FUNCTION ISTANBUL_MANUEL_SHIFT_TYPE()
RETURNS TABLE
AS
RETURN(
SELECT TOP(1) CITYNR, SHIFTTYPE AS EN_COK_TERCIH_EDILEN_VITES_TIPI, COUNT(SHIFTTYPE) AS TOPLAM_SAYISI
FROM PLATES
GROUP BY CITYNR, SHIFTTYPE
HAVING SHIFTTYPE IS NOT NULL AND SHIFTTYPE <> '-' AND SHIFTTYPE <> '' AND SHIFTTYPE = 'Düz Vites' AND CITYNR = 36
ORDER BY COUNT(SHIFTTYPE) DESC
);

--7. SEHIRLERE GORE EN FAZLA TERCIH EDILEN OTOMATIK VITES TIPI
CREATE FUNCTION ISTANBUL_AUTOMATIC_SHIFT_TYPE()
RETURNS TABLE
AS
RETURN(
SELECT TOP(1) CITYNR, SHIFTTYPE AS EN_COK_TERCIH_EDILEN_VITES_TIPI, COUNT(SHIFTTYPE) AS TOPLAM_SAYISI
FROM PLATES
GROUP BY CITYNR, SHIFTTYPE
HAVING SHIFTTYPE IS NOT NULL AND SHIFTTYPE <> '-' AND SHIFTTYPE <> '' AND SHIFTTYPE = 'Otomatik Vites' AND CITYNR = 36
ORDER BY TOPLAM_SAYISI DESC
);


SELECT * FROM MAX_BRAND_AND_MODEL();
SELECT * FROM MIN_CAR_COLOR();
SELECT * FROM MAX_LICENCE_DATE();
SELECT * FROM ISTANBUL_MIN_CAR();
SELECT * FROM HIGH_MOTOR_VOLUME();
SELECT * FROM ISTANBUL_MANUEL_SHIFT_TYPE();