--1. EN FAZLA OLAN MARKA VE MODEL.
SELECT TOP(1) COUNT(BRAND) AS MARKA_SAYISI, BRAND, MODEL 
FROM PLATES
GROUP BY BRAND, MODEL
ORDER BY COUNT(BRAND) DESC, COUNT(MODEL) DESC;

--2. EN AZ OLAN RENK.
SELECT TOP(1) COUNT(COLOR) AS RENK_ADETI, COLOR AS RENK
FROM PLATES
GROUP BY COLOR
HAVING COLOR IS NOT NULL AND COLOR <> '-'
ORDER BY COUNT(COLOR) ASC;

--3. LISANS TARIHI 2008 VEYA UST OLAN KAC MARKA VE MODEL OLDUGUNU BUL.
SELECT TOP(1)  LICENCEDATE, COUNT(BRAND), COUNT(MODEL)
FROM PLATES
GROUP BY LICENCEDATE
HAVING DATEPART(YEAR, LICENCEDATE) > 2008
ORDER BY LICENCEDATE;

--4. Ýstanbul'da en az hangi araç var?
SELECT TOP(1) CITYNR, BRAND AS MARKA, COUNT(BRAND) AS MARKA_SAYISI
FROM PLATES
WHERE CITYNR = 36
GROUP BY CITYNR, BRAND
ORDER BY CITYNR, COUNT(BRAND) ASC;

--5. EN FAZLA TERCIH EDILEN MOTOR HACMI
SELECT TOP(1) MOTORVOLUME AS EN_COK_TERCIH_EDILEN_MOTOR_HACMI, COUNT(MOTORVOLUME) AS TOPLAM_SAYISI
FROM PLATES
GROUP BY MOTORVOLUME
HAVING MOTORVOLUME IS NOT NULL AND MOTORVOLUME <> '-' AND MOTORVOLUME <> ''
ORDER BY COUNT(MOTORVOLUME) DESC;

--6. ISTANBUL'DA EN FAZLA TERCIH EDILEN DUZ VITES TIPI
SELECT TOP(1) CITYNR, SHIFTTYPE AS EN_COK_TERCIH_EDILEN_VITES_TIPI, COUNT(SHIFTTYPE) AS TOPLAM_SAYISI
FROM PLATES
GROUP BY CITYNR, SHIFTTYPE
HAVING SHIFTTYPE IS NOT NULL AND SHIFTTYPE <> '-' AND SHIFTTYPE <> '' AND SHIFTTYPE = 'Düz Vites' AND CITYNR = 36
ORDER BY COUNT(SHIFTTYPE) DESC;

--7. SEHIRLERE GORE EN FAZLA TERCIH EDILEN OTOMATIK VITES TIPI
SELECT TOP(1) CITYNR, SHIFTTYPE AS EN_COK_TERCIH_EDILEN_VITES_TIPI, COUNT(SHIFTTYPE) AS TOPLAM_SAYISI
FROM PLATES
GROUP BY CITYNR, SHIFTTYPE
HAVING SHIFTTYPE IS NOT NULL AND SHIFTTYPE <> '-' AND SHIFTTYPE <> '' AND SHIFTTYPE = 'Otomatik Vites' AND CITYNR = 36
ORDER BY TOPLAM_SAYISI DESC;